### ISSUE TITLE
🚀 Feature Request: Improve the customize button

### ISSUE THREAD

**Issue by saminabangash** [grey-software/Material-Math#68]
### Problem Overview 👁️‍🗨️ 

It may not be obvious to users that a pencil icon is meant to customize the practice session 

### What would you like? 🧰

- [x] The button should have an icon that can be familiar to users, such as a cog
![image](https://user-images.githubusercontent.com/73180133/96614020-186f7580-1319-11eb-965b-bab3a8d2858e.png)

- [x] Add a tooltip that indicates that this button customizes the practice session when hovered.

### What alternatives have you considered? 🔍

NA

### Additional details ℹ️

NA

**Comment by ArsalaBangash** [comment]
Let's also change the color of the icon to match the other icons #114489

**Comment by soumyankar** [comment]
Hey, I would like to fix this issue! 💯

**Comment by ArsalaBangash** [comment]
Good luck :D
