### ISSUE TITLE
🚀 Feature Request: Create a button that exits the customization page 

### ISSUE THREAD

**Issue by saminabangash** [grey-software/Material-Math#69]
### Problem Overview 👁️‍🗨️ 

Users cannot exit the customization screen before completing all the options
### What would you like? 🧰

An exit button to the left of the "Next" button on the customized page
### What alternatives have you considered? 🔍

I thought of adding an exit button to the top left, but there is already a customization progress indicator on the top of the screen
### Additional details ℹ️

NA

**Comment by soumyankar** [comment]
Hi,
I would like to contribute to the project I think I can solve this issue! I'll work on solving this issue right now!

**Comment by ArsalaBangash** [comment]
Hi @soumyankar , I've gone ahead and assign the issue to you :)
