### ISSUE TITLE
🚀 Feature Request: Add a play icon to the play button

### ISSUE THREAD

**Issue by saminabangash** [grey-software/Material-Math#70]
### Problem Overview 👁️‍🗨️ 

Including icons in key action-buttons is an important UI design pattern
### What would you like? 🧰

A play icon to the left of the play button"s label
### What alternatives have you considered? 🔍

NA
### Additional details ℹ️

NA

**Comment by saumyaaajain** [comment]
Hello, can I work on this?

**Comment by milindvishnoi** [comment]
Yes! Please assign yourself to the issue and submit a pull request whenever you are done.

**Comment by saumyaaajain** [comment]
@milindvishnoi please take a look at my PR
